services:
  hashcrypto-api:
    build:
      context: ./Core
      dockerfile: Dockerfile
    restart: no # always
    ports:
      - "5239:8080"
      - "5240:8081"

  hashcrypto-web:
    build:
      context: ./hash-crypto-app
      dockerfile: Dockerfile
    restart: no # always
    ports:
      - "4200:80"
